export const recommendedRules = {
  "react-component-architecture/component-folder-structure": "error",
  "react-component-architecture/index-must-reexport-default": "error",
  "react-component-architecture/no-state-in-component-body": "warn",
  "react-component-architecture/no-inline-jsx-functions": "error",
  "react-component-architecture/no-jsx-computation": "warn",
  "react-component-architecture/classnames-required": "error",
  "react-component-architecture/classnames-import-name": "error",
  "react-component-architecture/no-dark-mode-classes": "error",
  "react-component-architecture/interface-prefix-i": "error",
  "react-component-architecture/forwardref-display-name": "error",
  "react-component-architecture/stories-require-default-export": "error",
  "react-component-architecture/props-must-be-visual": "warn",
  "react-component-architecture/react-import-named": "error",
  "react-component-architecture/package-json-exact-deps": "error",
  "react-component-architecture/github-actions-permissions": "error",
  "react-component-architecture/no-untranslated-jsx-text": "warn",
  "react-component-architecture/query-keys-must-be-constant": "error",
  "react-component-architecture/no-cross-feature-imports": "error"
} as const;
