import type { TSESTree } from "@typescript-eslint/utils";

import { createRule } from "../utils/createRule";

export const RULE_NAME = "no-narration-comments";

type MessageIds = "narrationComment";

const NARRATION_PATTERNS: readonly RegExp[] = [
  /^here\s+we\b/iu,
  /^now\s+we\b/iu,
  /^first[,]?\s+(?:we\b|[a-z])/iu,
  /^then[,]?\s+(?:we\b|[a-z])/iu,
  /^next[,]?\s+(?:we\b|[a-z])/iu,
  /^finally[,]?\s+(?:we\b|[a-z])/iu,
  /^let's\b/iu,
  /^let\s+me\b/iu
];

function commentText(comment: TSESTree.Comment): string {
  if (comment.type === "Line") {
    return comment.value.trim();
  }
  return comment.value
    .split("\n")
    .map((line) => line.replace(/^\s*\*?/u, ""))
    .join(" ")
    .trim();
}

function looksLikeJsDoc(comment: TSESTree.Comment): boolean {
  return comment.type === "Block" && comment.value.startsWith("*");
}

export const noNarrationCommentsRule = createRule<[], MessageIds>({
  name: RULE_NAME,
  meta: {
    type: "suggestion",
    docs: {
      description:
        "Disallow narrative comments like 'Here we...', 'Now we...', 'First, we...'. These read as step-by-step prose and add no information a future reader can't get from the code itself. Often a tell that the comment was generated by an agent describing its own changes."
    },
    schema: [],
    messages: {
      narrationComment:
        "Narrative comment ({{snippet}}). Describe the WHY, not the sequence of operations — or delete the comment."
    }
  },
  defaultOptions: [],
  create(context) {
    return {
      Program() {
        const comments = context.sourceCode.getAllComments();

        for (const comment of comments) {
          if (looksLikeJsDoc(comment)) {
            continue;
          }
          const text = commentText(comment);
          if (text === "") {
            continue;
          }
          for (const pattern of NARRATION_PATTERNS) {
            if (pattern.test(text)) {
              const snippet =
                text.length > 40 ? `${text.slice(0, 40)}…` : text;
              context.report({
                loc: comment.loc,
                messageId: "narrationComment",
                data: { snippet }
              });
              break;
            }
          }
        }
      }
    };
  }
});
